#define MAINPREFIX x
#define PREFIX ELD_magicTriangle

#include "script_version.hpp"

#define VERSION MAJOR.MINOR.PATCHLVL.BUILD
#define VERSION_AR MAJOR,MINOR,PATCHLVL,BUILD

#define REQUIRED_VERSION 2.10
#define REQUIRED_CBA_VERSION { 3, 5, 0 }
#define REQUIRED_ACE_VERSION { 3, 11, 0 }

#define QMAIN_ADDON QUOTE(MAIN_ADDON)
#define QCOMPONENT QUOTE(COMPONENT)
#define QADDON QUOTE(ADDON)

#define EADDON(PVAR) DOUBLES(PREFIX,PVAR)
#define QEADDON(PVAR) QUOTE(EADDON(PVAR))

#define AUTHOR { "EL_D148L0" }
#define QAUTHOR QUOTE(AUTHOR)
